
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coffetory_development

test: 
  <<: *default
  database: coffetory_test

production:
   <<: *default
   database: coffetory_production
   username: psialedev
   password: